# Load aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# Load private environment variables
if [ -e "$HOME/.private_environment" ]; then
  source "$HOME/.private_environment"
fi

# Ignore duplicate history entries
setopt histignoredups

# Allow comments in shell
setopt interactivecomments

# Automatically change into directories without `cd`
setopt auto_cd

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# Enable extended globbing
setopt EXTENDED_GLOB

# Use nvim as an editor
export EDITOR='nvim'
export VISUAL='nvim'

# Default terminal
export TERMINAL='alacritty'

source ${HOME}/.igloo.zsh
source ${HOME}/.git-prompt.sh

# Configure lab completions
source <(lab completion zsh)

# Load zsh completions installed by apps
fpath+=/home/mike/.zsh_functions

# Configure NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Load nord dircolors for ls, tree, etc
test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)

# Ssh agent magic
eval `keychain --eval --quiet --ignore-missing --agents ssh id_ed25519`

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Deno
# export DENO_INSTALL="/home/mike/.deno"
# export PATH="$DENO_INSTALL/bin:$PATH"

# bun completions
[ -s "/home/mike/.bun/_bun" ] && source "/home/mike/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# pnpm
export PNPM_HOME="/home/mike/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
