#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all
Mod=Mod4
Alt=Mod1

herbstclient keybind $Mod-Control-Shift-l spawn dm-tool switch-to-greeter

hc keybind Control+Shift+$Mod+q spawn sudo reboot
hc keybind Control+Shift+$Mod+z spawn sudo shutdown -h now

hc keybind Control-$Mod-1 spawn amixer set Master 5%-
hc keybind Control-$Mod-2 spawn amixer set Master 5%+

hc keybind $Mod-Escape spawn dunstctl close
hc keybind Control-$Mod-Escape spawn dunstctl close-all
hc keybind Control-$Mod-Shift-Escape spawn dunstctl history-pop
hc keybind Control-$Mod-n spawn /home/mike/code/dotfiles/bin/toggle-notifications.sh
hc keybind $Mod-Shift-u spawn /home/mike/code/dotfiles/bin/unsplit.sh

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

hc keybind Control-Shift-$Mod-z spawn /home/mike/code/dotfiles/bin/clear-tag.sh

hc keybind Control-Shift-$Mod-c spawn /home/mike/code/dotfiles/bin/copy-mouse-coordinates.sh
hc keybind Control-Shift-$Mod-t spawn /home/mike/code/dotfiles/bin/copy-timestamp.py

hc keybind $Mod-m set_attr clients.focus.minimized toggle
hc keybind $Mod-Shift-m spawn rofi -show windowcd -modi windowcd,window

default_term='alacritty'
hc keybind $Mod-Return spawn ${TERMINAL:-$default_term}

hc keybind $Mod-d spawn rofi -show drun -sort -matching fuzzy -sorting-method fzf
hc keybind $Mod-Shift-d spawn rofi -show run

hc keybind $Mod-b spawn /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chrome --file-forwarding com.google.Chrome --enable-features=WebUIDarkMode --force-dark-mode
hc keybind $Mod-n spawn /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chrome --file-forwarding com.google.Chrome -incognito --enable-features=WebUIDarkMode --force-dark-mode

hc keybind $Mod-Shift-b spawn brave --profile-directory=Default
hc keybind $Mod-Shift-n spawn brave --profile-directory=Default -incognito

hc keybind Control-Shift-Print spawn flameshot gui
hc keybind Control-Print spawn flameshot screen

hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode

resize_step=0.01
hc keybind $Mod-Control-h       resize left +$resize_step
hc keybind $Mod-Control-j       resize down +$resize_step
hc keybind $Mod-Control-k       resize up +$resize_step
hc keybind $Mod-Control-l       resize right +$resize_step

hc set_attr settings.default_frame_layout max
hc load '(clients max:0)'

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc or , attr theme.title_height 0 , hc attr theme.title_height 0

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        # if [ "$i" = "0" ] ; then
        #   hc keybind "$Mod-$key" chain , use_index "$i" , attr theme.title_height 0 , hc attr theme.title_depth 0
        # else
        #   hc keybind "$Mod-$key" chain , use_index "$i" , attr theme.title_height 40 , hc attr theme theme.padding_top 40
        # fi
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

move_floated_step=30
hc keybind Control-Alt-h spawn hc_move_floated x-axis +$move_floated_step
hc keybind Control-Alt-j spawn hc_move_floated y-axis -$move_floated_step
hc keybind Control-Alt-k spawn hc_move_floated y-axis +$move_floated_step
hc keybind Control-Alt-l spawn hc_move_floated x-axis -$move_floated_step

resize_floated_step=30
hc keybind Control-Alt-Shift-h spawn hc_resize_floated x-axis +$resize_floated_step
hc keybind Control-Alt-Shift-j spawn hc_resize_floated y-axis -$resize_floated_step
hc keybind Control-Alt-Shift-k spawn hc_resize_floated y-axis +$resize_floated_step
hc keybind Control-Alt-Shift-l spawn hc_resize_floated x-axis -$resize_floated_step

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle

# Cycle all layouts
hc keybind $Mod-Shift-space \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 vertical horizontal max vertical grid \
               , cycle_layout +1
# Cycle horizontal and maximized
hc keybind $Mod-space \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 horizontal max \
               , cycle_layout +1

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Cycle clients
hc keybind $Mod-Tab                 cycle +1
hc keybind $Mod-Shift-Tab           cycle -1
# Cycle all clients
hc keybind $Mod-Control-Tab         cycle_all +1
hc keybind $Mod-Control-Shift-Tab   cycle_all -1

# Constrain fullscreen inside frame
hc keybind $Mod-Control-f chain \
  , attr clients.focus.ewmhrequests off \
  , attr clients.focus.ewmhnotify on \
  , attr clients.focus.fullscreen on \
  , attr clients.focus.ewmhnotify off \
  , set_attr clients.focus.fullscreen off \
  , set_attr clients.focus.ewmhnotify on \
  , sprintf CMD 'sleep 2 ; herbstclient attr clients.%s.ewmhrequests on' clients.focus.winid spawn bash -c CMD

background_color='#000000'
active_border_color='#ffffff'
urgent_color='#B48EAD'

xsetroot -solid $background_color

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $background_color
hc set frame_border_normal_color $background_color
hc set frame_bg_normal_color $background_color
hc set frame_bg_active_color $active_border_color
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 4
hc set frame_gap 0
hc set window_gap 0
hc set frame_padding 0

hc attr theme.title_height 0
hc attr theme.title_depth 10
hc attr theme.title_font 'Fira Code:pixelsize=14:bold'
hc attr theme.title_color $active_border_color
hc attr theme.active.color $background_color
hc attr theme.normal.color $background_color
hc attr theme.urgent.color $urgent_color
hc attr theme.inner_width 1
hc attr theme.inner_color $background_color
hc attr theme.border_width 4
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 1
hc attr theme.active.inner_color $active_border_color
hc attr theme.urgent.inner_color $background_color
hc attr theme.normal.inner_color $background_color
hc attr theme.active.outer_color $background_color
hc attr theme.urgent.outer_color $background_color
hc attr theme.normal.outer_color $background_color
hc attr theme.active.outer_width 1
hc attr theme.background_color $background_color

hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# Toggle title
hc keybind $Mod-t or . \
    and , compare theme.title_height = 0 , attr theme.title_height 25 \
    . \
    and , compare theme.title_height = 25 , attr theme.title_height 0


hc keybind $Mod-Shift-s spawn /home/mike/code/dotfiles/bin/toggle_borders_and_spacing.sh

hc unrule -F
hc rule focus=on
hc rule floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on


hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=gnome-calculator floating=on
hc rule class=kclock floating=on
hc rule class=flipclock floating=on
hc rule class=Gcr-prompter floating=on
hc rule class=TelegramDesktop floatplacement=smart
hc rule class=scrcpy floating=on

xdg-settings set default-web-browser com.google.Chrome.desktop
xdg-mime default com.google.Chrome.desktop x-scheme-handler/http
xdg-mime default com.google.Chrome.desktop x-scheme-handler/https

hc set tree_style '╾│ ├└╼─┐'

hc unlock
